sudo: required
language: node_js
cache:
  yarn: true
  pip: true
  directories:
  - ".peru"
node_js:
- '10'
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
- pyenv install -s 3.6
- pyenv shell 3.6
- pip3 install peru
- peru sync --force
install:
- yarn --ignore-engines
- yarn build:webdriver
- yarn build:selianize
- yarn build:ext:prod
script:
- echo $keypem | base64 -d > packages/selenium-ide/key.pem
- cd packages/selenium-ide
- ./build.sh build/ key.pem
deploy:
  provider: releases
  api_key:
    secure: KLsmn3/wwFtipSV3Pu/27+RQonTtHjCC07+KzEr4NjnmAJ0Vmzdwk2iMFZfqHEkJT3xD4FNEjzhPIx7YG0tPT/1AFaLT57omEgB2N9Usre+kN/4pAny04wM8wJ8V1lXvl/sqApaI9LN5dvUu/b4DCMRRRFcc/eWyBHyIJ3cmLCRgzUjg696/QCKqsz8LiLd52GLXxeI4b0YkJnOnWTmGjtSdjG7oRc/Z1aF9XZQ/0P4TaIHHtmbFsnYJ0rGPOAUwlti0zEnTKTROtWu4Uv4WTF/vcheZ37ot8bdrju0PyHfh0sNde5jXDgt+wn9njiSoZxa0PPelQfVrnR2QbazL3GfqsRUHxbQxSRfSGp+EdmXQ0krcXP35OM+psjy+ER5w/T/0wVZ3ZSx/aFRyYEKk7CVtMg92TMkXcQHbaZQiZ1jJuEIkY9J8LzxjzoHptRZapZWu2BgXB7uROjiyYpk+cx6F4r1JXecNSEo17laM2SVofC3Amk7jEIKS25+luvNcECvczEJpKJnwGn5PUKHPbNaW/n6wmAiWc7g1Y372IpjhojhSh2ExBaPFF0alhwvR4d6PFN1dbYn/vj7yDPjHd6dePFpHlwLS4peM9JU5y5q98/1uZ3xMmg0ARBTaoEpC0L4LqukLmLj2AMdzlQvsVx11/ytUpy9ugzP7EIR+gdo=
  file: packages/selenium-ide/build.crx
  on:
    repo: superbothq/superbot-recorder-chrome
    branch: superbot
